/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/challenges": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_challenges"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/challenges/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["one"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/devices": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_devices"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/devices/{public_key}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["revoke"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["health"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/items": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_items"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/items/{id}/purchase": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["buy"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/leaderboard": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["standings"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/passes/apple": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["issue"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/passes/apple/challenge": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["challenge"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/passes/token": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["token"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/portal/assets": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["library"];
    put?: never;
    post: operations["upload"];
    delete: operations["drop_asset"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/portal/catalog/reload": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["catalog_reload"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/portal/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["me"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/portal/sign-out": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["sign_out"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/portal/sql": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["sql"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/portal/sql/script": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["sql_script"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/portal/tables": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["tables"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/portal/tables/{table}/rows": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["rows"];
    put?: never;
    post: operations["insert_row"];
    delete: operations["delete_row"];
    options?: never;
    head?: never;
    patch: operations["update_row"];
    trace?: never;
  };
  "/api/portal/trade/items": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["trade_items"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/portal/trade/items/{id}/options": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["trade_options"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/portal/trade/orders": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["trade_orders"];
    put?: never;
    post: operations["trade_buy"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/portal/trade/orders/{purchase_id}/delivery": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["trade_fulfil"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/portal/trade/orders/{purchase_id}/refund": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["trade_refund"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/portal/trade/pass": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["trade_pass"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/purchases/{id}/refund": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["give_back"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/register_tap": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["register"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/staff/card": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["read"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/staff/card/{card_id}/challenge": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["link"];
    post?: never;
    delete: operations["unlink"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/staff/card/{card_id}/location": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["place"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/users/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["me"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/users/me/anonymous": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["anonymous"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/users/me/daily": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["today"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/users/me/dorm": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["dorm"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/users/me/purchases": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["mine"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/users/me/tokens": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["balances"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/challenge": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["challenge"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/device": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["verify"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/device/enroll": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["enroll"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["status"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AnonymousBody: {
      anonymous: boolean;
    };
    AssetView: {
      /** Format: int64 */
      bytes: number;
      content_type: string;
      /** Format: date-time */
      created_at: string;
      filename?: string | null;
      key: string;
      kind: string;
      uploaded_by: string;
      url: string;
    };
    AuthErrBody: {
      error: string;
    };
    Balances: {
      day?: string | null;
      /** Format: int64 */
      scottycoins: number;
      /** Format: int64 */
      thistlestones: number;
    };
    Board: {
      challenges: components["schemas"]["ChallengeView"][];
      cleared: number;
      total: number;
    };
    Bought: {
      /** Format: int64 */
      cost: number;
      item: string;
      /** Format: uuid */
      item_id: string;
      options: components["schemas"]["DeskPickView"][];
      /** Format: int64 */
      purchase_id: number;
      /** Format: int64 */
      quantity: number;
      /** Format: int64 */
      scottycoins: number;
      /** Format: int64 */
      spent: number;
      /** Format: int64 */
      stock: number;
    };
    BuyBody: {
      options?: components["schemas"]["PickBody"][];
      /** Format: int64 */
      quantity?: number;
    };
    /** @enum {string} */
    Capability: "portal" | "sql_console" | "data_console" | "card_desk" | "trade_desk" | "assets";
    CardUrl: {
      url: string;
    };
    CardView: {
      card_id: string;
      /** Format: uuid */
      challenge_id?: string | null;
      /** Format: double */
      lat?: number | null;
      /** Format: double */
      lon?: number | null;
    };
    Challenge: {
      /** Format: int64 */
      expires_in: number;
      nonce: string;
    };
    ChallengeView: {
      category: string;
      cleared: boolean;
      /** Format: int64 */
      coin_value: number;
      description: string;
      id: string;
      location?: null | components["schemas"]["Location"];
      name: string;
      open_from: string;
      tagline: string;
    };
    Column: {
      default_expr?: string | null;
      generated: boolean;
      /** Format: int32 */
      key: number;
      kind: string;
      name: string;
      nullable: boolean;
    };
    Cup: {
      community: string;
      /** Format: int64 */
      earned: number;
      /** Format: double */
      percent: number;
      /** Format: int64 */
      target: number;
    };
    DailyView: {
      challenge?: null | components["schemas"]["ChallengeView"];
      day: string;
    };
    DeskPickBody: {
      /** Format: uuid */
      option_id: string;
      value: string;
    };
    DeskPickView: {
      label: string;
      value: string;
    };
    DeskRefundBody: {
      andrew_id: string;
      /** Format: int64 */
      quantity: number;
    };
    DeskSaleBody: {
      andrew_id: string;
      /** Format: uuid */
      item_id: string;
      options?: components["schemas"]["DeskPickBody"][];
      /** Format: int64 */
      quantity: number;
    };
    DeviceView: {
      created_at: string;
      label?: string | null;
      public_key: string;
    };
    DormBody: {
      dorm: string;
    };
    DropBody: {
      key: string;
    };
    EditBody: {
      key: {
        [key: string]: unknown;
      };
      set: {
        [key: string]: unknown;
      };
    };
    Enroll: {
      ticket: string;
    };
    Enrolled: {
      enrolled: boolean;
      public_key: string;
    };
    FulfilBody: {
      delivered: boolean;
    };
    Fulfilled: {
      /** Format: int64 */
      purchase_id: number;
      /** Format: date */
      received_item_date?: string | null;
    };
    GaveBack: {
      /** Format: int64 */
      refunded: number;
      /** Format: int64 */
      scottycoins: number;
    };
    Grant: {
      level: components["schemas"]["Level"];
      table: string;
    };
    Health: {
      status: string;
    };
    Identity: {
      andrew_id: string;
      capabilities: components["schemas"]["Capability"][];
      email?: string | null;
      groups: string[];
      name: string;
      roles: components["schemas"]["Role"][];
      tables: components["schemas"]["Grant"][];
    };
    IssueBody: {
      /** Format: int64 */
      issued_at?: number | null;
      signature?: string | null;
    };
    ItemView: {
      background_url?: string | null;
      /** Format: int64 */
      cost: number;
      description: string;
      icon_shade?: string | null;
      id: string;
      image_url?: string | null;
      name: string;
      options: components["schemas"]["OptionView"][];
      /** Format: int64 */
      stock: number;
    };
    KeyBody: {
      key: {
        [key: string]: unknown;
      };
    };
    /** @enum {string} */
    Level: "none" | "read" | "edit" | "full";
    Library: {
      accepts: string[];
      assets: components["schemas"]["AssetView"][];
      kinds: string[];
      /** Format: int64 */
      max_bytes: number;
      ready: boolean;
    };
    LinkBody: {
      /** Format: uuid */
      challenge_id: string;
    };
    Location: {
      /** Format: double */
      lat: number;
      /** Format: double */
      lon: number;
    };
    LogoutResponse: {
      end_session_url?: string | null;
    };
    OptionBody: {
      choices?: string[];
      kind: string;
      label: string;
      required?: boolean;
    };
    OptionView: {
      choices: string[];
      id: string;
      kind: string;
      label: string;
      required: boolean;
    };
    OptionsBody: {
      options: components["schemas"]["OptionBody"][];
    };
    OrderView: {
      andrew_id: string;
      /** Format: int64 */
      cost: number;
      item: string;
      /** Format: uuid */
      item_id: string;
      options: components["schemas"]["DeskPickView"][];
      /** Format: int64 */
      purchase_id: number;
      /** Format: int64 */
      quantity: number;
      /** Format: date */
      received_item_date?: string | null;
      /** Format: uuid */
      user_id: string;
    };
    Outcome: {
      columns: string[];
      /** Format: int64 */
      elapsed_ms: number;
      read_only: boolean;
      rows: components["schemas"]["Value"][];
      /** Format: int64 */
      rows_affected: number;
      truncated: boolean;
    };
    Page: {
      columns: components["schemas"]["Column"][];
      key: string[];
      /** Format: int64 */
      limit: number;
      /** Format: int64 */
      offset: number;
      rows: components["schemas"]["Value"][];
      table: string;
      /** Format: int64 */
      total: number;
    };
    PassChallenge: {
      andrew_id: string;
      /** Format: int64 */
      issued_at: number;
      message: string;
    };
    PassHolder: {
      andrew_id: string;
      dorm?: string | null;
      /** Format: int64 */
      issued_at?: number | null;
      name: string;
      orders: components["schemas"]["OrderView"][];
      /** Format: int64 */
      scottycoins: number;
      /** Format: int64 */
      thistlestones: number;
      /** Format: uuid */
      user_id: string;
      verified: boolean;
    };
    PassLookup: {
      andrew_id?: string | null;
      token?: string | null;
    };
    PassToken: {
      andrew_id: string;
      /** Format: int64 */
      issued_at: number;
      name: string;
      token: string;
    };
    PickBody: {
      option_id: string;
      value: string;
    };
    PickedView: {
      label: string;
      value: string;
    };
    PlaceBody: {
      /** Format: double */
      lat: number;
      /** Format: double */
      lon: number;
    };
    PortalErrBody: {
      detail?: string | null;
      error: string;
    };
    Profile: {
      andrew_id: string;
      anonymous: boolean;
      created_at: string;
      dorm?: string | null;
      player: boolean;
    };
    PurchaseView: {
      /** Format: int64 */
      cost: number;
      delivered: boolean;
      image_url?: string | null;
      item_id: string;
      name: string;
      options: components["schemas"]["PickedView"][];
      /** Format: int64 */
      purchase_id: number;
      /** Format: int64 */
      quantity: number;
    };
    Purchased: {
      /** Format: int64 */
      cost: number;
      item_id: string;
      name: string;
      options: components["schemas"]["PickedView"][];
      /** Format: int64 */
      purchase_id: number;
      /** Format: int64 */
      quantity: number;
      /** Format: int64 */
      scottycoins: number;
      /** Format: int64 */
      spent: number;
      /** Format: int64 */
      stock: number;
    };
    RefundBody: {
      /** Format: int64 */
      quantity?: number;
    };
    RefundView: {
      /** Format: int64 */
      refunded: number;
      /** Format: int64 */
      scottycoins: number;
    };
    Registered: {
      challenge: components["schemas"]["ChallengeView"];
      /** Format: int64 */
      current_scottycoins: number;
      /** Format: int64 */
      current_thistlestones: number;
      first: boolean;
      /** Format: int64 */
      place: number;
    };
    Reloaded: {
      tables: number;
    };
    Revoked: {
      revoked: boolean;
    };
    /** @enum {string} */
    Role: "admins" | "orientation-staff" | "trade-admin" | "challenge-placer";
    Row: {
      community?: string | null;
      name: string;
      /** Format: int64 */
      rank: number;
      /** Format: int64 */
      score: number;
      you: boolean;
    };
    RowBody: {
      row: {
        [key: string]: unknown;
      };
    };
    Script: {
      committed: boolean;
      /** Format: int64 */
      elapsed_ms: number;
      failed?: number | null;
      read_only: boolean;
      statements: number;
      steps: components["schemas"]["Step"][];
    };
    Shelf: {
      items: components["schemas"]["ItemView"][];
      total: number;
    };
    ShopItem: {
      background_url?: string | null;
      /** Format: int64 */
      cost: number;
      description: string;
      icon_shade?: string | null;
      /** Format: uuid */
      id: string;
      image_url?: string | null;
      name: string;
      options: components["schemas"]["ShopOption"][];
      /** Format: int64 */
      stock: number;
    };
    ShopOption: {
      choices: string[];
      /** Format: uuid */
      id: string;
      kind: string;
      label: string;
      required: boolean;
    };
    SignedOut: {
      signed_out: boolean;
    };
    SqlBody: {
      sql: string;
      write?: boolean;
    };
    Standings: {
      cup?: null | components["schemas"]["Cup"];
      metric: string;
      rows: components["schemas"]["Row"][];
      you?: null | components["schemas"]["You"];
    };
    Step: {
      error?: string | null;
      outcome?: null | components["schemas"]["Outcome"];
      statement: string;
    };
    TableView: {
      columns: components["schemas"]["Column"][];
      key: string[];
      level: components["schemas"]["Level"];
      name: string;
    };
    TapBody: {
      /** Format: float */
      accuracy?: number | null;
      /** Format: double */
      lat?: number | null;
      /** Format: double */
      lon?: number | null;
      url: string;
    };
    Ticket: {
      /** Format: int64 */
      expires_in: number;
      ticket: string;
    };
    Uploaded: {
      key: string;
      url: string;
    };
    UserView: {
      admin: boolean;
      andrew_id: string;
      email?: string | null;
      groups: string[];
      name: string;
      staff: boolean;
    };
    Value: unknown;
    Verify: {
      label?: string | null;
      nonce: string;
      public_key: string;
      signature: string;
    };
    Wallet: {
      purchases: components["schemas"]["PurchaseView"][];
    };
    Written: {
      rows: components["schemas"]["Value"][];
    };
    You: {
      community?: string | null;
      /** Format: int64 */
      rank: number;
      /** Format: int64 */
      score: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  list_challenges: {
    parameters: {
      query?: {
        category?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Board"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
    };
  };
  one: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Challenge id */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChallengeView"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
    };
  };
  list_devices: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DeviceView"][];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
    };
  };
  revoke: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Device public key */
        public_key: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Revoked"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
    };
  };
  health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
    };
  };
  list_items: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Shelf"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
    };
  };
  buy: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Item id */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BuyBody"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Purchased"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
    };
  };
  standings: {
    parameters: {
      query?: {
        metric?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Standings"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
    };
  };
  issue: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["IssueBody"];
      };
    };
    responses: {
      /** @description An Apple Wallet pass */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/vnd.apple.pkpass": unknown;
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
    };
  };
  challenge: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PassChallenge"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
    };
  };
  token: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["IssueBody"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PassToken"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
    };
  };
  library: {
    parameters: {
      query?: {
        kind?: string | null;
        limit?: number | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Library"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortalErrBody"];
        };
      };
    };
  };
  upload: {
    parameters: {
      query: {
        kind: string;
        name?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/octet-stream": number[];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Uploaded"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortalErrBody"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortalErrBody"];
        };
      };
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortalErrBody"];
        };
      };
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortalErrBody"];
        };
      };
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortalErrBody"];
        };
      };
    };
  };
  drop_asset: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DropBody"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Uploaded"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortalErrBody"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortalErrBody"];
        };
      };
    };
  };
  catalog_reload: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Reloaded"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortalErrBody"];
        };
      };
    };
  };
  me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Identity"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortalErrBody"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortalErrBody"];
        };
      };
    };
  };
  sign_out: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SignedOut"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortalErrBody"];
        };
      };
    };
  };
  sql: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SqlBody"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Outcome"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortalErrBody"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortalErrBody"];
        };
      };
    };
  };
  sql_script: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SqlBody"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Script"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortalErrBody"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortalErrBody"];
        };
      };
    };
  };
  tables: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TableView"][];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortalErrBody"];
        };
      };
    };
  };
  rows: {
    parameters: {
      query?: {
        limit?: number | null;
        offset?: number | null;
        order?: string | null;
        desc?: boolean | null;
        search?: string | null;
      };
      header?: never;
      path: {
        /** @description Table name */
        table: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Page"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortalErrBody"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortalErrBody"];
        };
      };
    };
  };
  insert_row: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Table name */
        table: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RowBody"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Written"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortalErrBody"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortalErrBody"];
        };
      };
    };
  };
  delete_row: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Table name */
        table: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["KeyBody"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Written"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortalErrBody"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortalErrBody"];
        };
      };
    };
  };
  update_row: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Table name */
        table: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EditBody"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Written"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortalErrBody"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortalErrBody"];
        };
      };
    };
  };
  trade_items: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ShopItem"][];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortalErrBody"];
        };
      };
    };
  };
  trade_options: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Item id */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OptionsBody"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ShopOption"][];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortalErrBody"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortalErrBody"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortalErrBody"];
        };
      };
    };
  };
  trade_orders: {
    parameters: {
      query?: {
        andrew_id?: string | null;
        delivered?: boolean | null;
        limit?: number | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrderView"][];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortalErrBody"];
        };
      };
    };
  };
  trade_buy: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DeskSaleBody"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Bought"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortalErrBody"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortalErrBody"];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortalErrBody"];
        };
      };
    };
  };
  trade_fulfil: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Purchase id */
        purchase_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FulfilBody"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Fulfilled"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortalErrBody"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortalErrBody"];
        };
      };
    };
  };
  trade_refund: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Purchase id */
        purchase_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DeskRefundBody"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GaveBack"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortalErrBody"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortalErrBody"];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortalErrBody"];
        };
      };
    };
  };
  trade_pass: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PassLookup"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PassHolder"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortalErrBody"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortalErrBody"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortalErrBody"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortalErrBody"];
        };
      };
    };
  };
  give_back: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Purchase id */
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RefundBody"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RefundView"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
    };
  };
  register: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TapBody"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Registered"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
    };
  };
  read: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CardUrl"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CardView"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
    };
  };
  link: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Uppercase hex card UID */
        card_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LinkBody"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CardView"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
    };
  };
  unlink: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Uppercase hex card UID */
        card_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CardView"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
    };
  };
  place: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Uppercase hex card UID */
        card_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PlaceBody"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CardView"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
    };
  };
  me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Profile"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
    };
  };
  anonymous: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AnonymousBody"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AnonymousBody"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
    };
  };
  today: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DailyView"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
    };
  };
  dorm: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DormBody"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DormBody"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
    };
  };
  mine: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Wallet"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
    };
  };
  balances: {
    parameters: {
      query?: {
        day?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Balances"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
    };
  };
  challenge: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Challenge"];
        };
      };
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
    };
  };
  verify: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Verify"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Ticket"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
    };
  };
  enroll: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Enroll"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Enrolled"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LogoutResponse"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
    };
  };
  status: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserView"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthErrBody"];
        };
      };
    };
  };
}
