//! `SeaORM` entities, generated by `sea-orm-codegen` from the live schema:
//!
//! ```sh
//! sea-orm-cli generate entity -o crates/entity/src --lib
//! ```
//!
//! Nothing is defined yet, the first migration has to land before there is a
//! schema to generate from.
