//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "challenges")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub category: String,
    #[sea_orm(column_type = "Text")]
    pub location: String,
    pub scotty_coins: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub maps_link: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub tagline: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub more_info_link: Option<String>,
    pub unlock_timestamp: DateTime,
    #[sea_orm(column_type = "Text")]
    pub secret: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::completion::Entity")]
    Completion,
}

impl Related<super::completion::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Completion.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        super::completion::Relation::User.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::completion::Relation::Challenges.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
