use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

// Content of "O-Quest Content (2026) - All Challenges.csv": name, tagline,
// description, category, and the published unlock time (Eastern, UTC-4), matching
// what quest-import reads. The one CSV row without a challenge name is left out.
//
// Ids are derived from the name, so a seed lands on the same rows everywhere and
// `down` can tell what this migration wrote. Coin value follows quest-import's
// default. Nothing is written if the table already holds challenges -- an
// environment that imported its own content keeps it.
const SEED: &str = r#"
            INSERT INTO "challenge"
                ("id", "name", "tagline", "description", "category", "coin_value", "open_from")
            SELECT
                md5('oquest-2026:' || seed."name")::uuid,
                seed."name",
                seed."tagline",
                seed."description",
                seed."category",
                5,
                seed."open_from"
            FROM (VALUES
                    ('The Hubbub At The Hub',
                     'Head to The Hub to learn more about enrollment services!',
                     'The HUB delivers comprehensive services and counsel to students and families for matters related to financial aid, billing and payments, ID cards, and registration and academic records. In direct support of student enrollment and persistence, The HUB values personal attention and focuses on providing technologically responsive tools in a professional, forward-thinking and accessible environment.',
                     'essentials', TIMESTAMPTZ '2026-08-16 18:00:00-04'),
                    ('Computer Serving You',
                     'Visit the Office of the CIO to learn about CMU''s Computing Services!',
                     'The Office of the CIO is committed to providing Carnegie Mellon University''s students, faculty, and staff with the IT environment that they expect from one of the world''s leading private universities.',
                     'essentials', TIMESTAMPTZ '2026-08-16 18:00:00-04'),
                    ('Accomodation Station',
                     'Find the Office of Disability Resources!',
                     'The Office of Disability Resources provides vibrant and accessible resources on disability issues for all members of the CMU community. Their mission includes providing physical, digital and programmatic campus access to all events and information within the Carnegie Mellon community for students and visitors to our campus. They work to ensure that qualified individuals receive reasonable accommodations as guaranteed by the Americans with Disabilities Act (ADA) and Section 504 of the Rehabilitation Act of 1973.',
                     'essentials', TIMESTAMPTZ '2026-08-16 18:00:00-04'),
                    ('Doctor''s Visit',
                     'Visit the University Health Services!',
                     'Carnegie Mellon''s University Health Services (UHS) is dedicated to enhancing students'' well-being through convenient access to healthcare, including sexual and reproductive health. Three Wellness to Go vending machines are available on campus.',
                     'essentials', TIMESTAMPTZ '2026-08-16 18:00:00-04'),
                    ('Somebody To Lean On',
                     'Check out the Counseling and Psychological Services!',
                     'Counseling and Psychological Services (CaPS) provides a safe, confidential environment for students to talk about personal and academic concerns. All students currently enrolled at the Pittsburgh campus are eligible for services at CaPS at no additional cost to them, and all services are confidential. Call CaPs at 412-268-2922.',
                     'essentials', TIMESTAMPTZ '2026-08-16 18:00:00-04'),
                    ('Can''t Stop The Center',
                     'Visit The Center for Student Diversity and Inclusion in the Cohon University Center!',
                     'The Center for Student Diversity and Inclusion actively cultivates a strong, diverse and inclusive community capable of living out these values and advancing research, creativity, learning and development that changes the world. The Center offers resources to enhance an inclusive and transformative student experience in areas such as campus climate and intergroup dialogue. Additionally, the Center supports and connects historically underrepresented students and first-generation college students in a setting where students’ differences and talents are appreciated and reinforced.',
                     'essentials', TIMESTAMPTZ '2026-08-16 18:00:00-04'),
                    ('Color Printing Power: Wean Hall',
                     'Find the Color Printer in Wean Hall Floor 5!',
                     'The Campus Printing service allows you to print from your computer or mobile phone to printers across campus. Send the file to the printer, then release the job at the printer by tapping your CMU ID. Central print release stations are available in computer labs, university libraries, some resident halls and public areas across campus. Some locations offer color printing, special paper sizes, scanning and copying. All students, faculty and staff are allotted a $40/semester print quota, which is associated with your CMU ID and debited when you release a print job at a campus printer. Computing Services also consults with departments to add departmental printers to the central print service.',
                     'essentials', TIMESTAMPTZ '2026-08-17 12:00:00-04'),
                    ('You''ve Got Mail!',
                     'Pick up or deliver some mail in the Cohon University Center!',
                     'You can send mail to and from Carnegie Mellon University at the University Center Mailroom. Postal Services is CMU''s full-service United States Postal Service (USPS) mailing and shipping facility.',
                     'essentials', TIMESTAMPTZ '2026-08-17 12:00:00-04'),
                    ('Let''s Be Financially Responsible!',
                     'Do some banking at the PNC Bank in the Cohon University Center!',
                     'Carnegie Mellon has an agreement with PNC to provide the campus community with convenient banking options, located on the lower level of the CUC. Visit here for your banking needs!',
                     'essentials', TIMESTAMPTZ '2026-08-17 12:00:00-04'),
                    ('Color Printing Power: Sorrells Library',
                     'Find the Color Printer in Sorrells Library!',
                     'The Campus Printing service allows you to print from your computer or mobile phone to printers across campus. Send the file to the printer, then release the job at the printer by tapping your CMU ID. Central print release stations are available in computer labs, university libraries, some resident halls and public areas across campus. Some locations offer color printing, special paper sizes, scanning and copying. All students, faculty and staff are allotted a $40/semester print quota, which is associated with your CMU ID and debited when you release a print job at a campus printer. Computing Services also consults with departments to add departmental printers to the central print service.',
                     'essentials', TIMESTAMPTZ '2026-08-17 12:00:00-04'),
                    ('W-E-L-L To Go! CUC Edition',
                     'Find the Wellness To-Go Vending Machine in the UC!',
                     'Carnegie Mellon''s University Health Services (UHS) is dedicated to enhancing students'' well-being through convenient access to healthcare, including sexual and reproductive health. Three Wellness To-Go vending machines are available on campus.',
                     'essentials', TIMESTAMPTZ '2026-08-18 12:00:00-04'),
                    ('W-E-L-L To Go! Tepper Edition',
                     'Find the Wellness To-Go Vending Machine in Tepper!',
                     'Carnegie Mellon''s University Health Services (UHS) is dedicated to enhancing students'' well-being through convenient access to healthcare, including sexual and reproductive health. Three Wellness To-Go vending machines are available on campus.',
                     'essentials', TIMESTAMPTZ '2026-08-18 12:00:00-04'),
                    ('W-E-L-L To Go! Highmark Edition',
                     'Find the Wellness To-Go Vending Machine in the Highmark Center!',
                     'Carnegie Mellon''s University Health Services (UHS) is dedicated to enhancing students'' well-being through convenient access to healthcare, including sexual and reproductive health. Three Wellness To-Go vending machines are available on campus.',
                     'essentials', TIMESTAMPTZ '2026-08-18 12:00:00-04'),
                    ('Well-being Lab Period',
                     'Reduce your stress in the Well-being Lab, located in the Highmark Center.',
                     'The Wellness Lab brings together traditional and modern techniques with the latest technology for a data-driven, well-rounded approach to health. You can explore wellness in various cultures and even participate in practices like stress reduction training.',
                     'essentials', TIMESTAMPTZ '2026-08-18 12:00:00-04'),
                    ('Contemplation Nooks',
                     'Take a breather in one of the Contemplation Nooks, located in the Highmark Center.',
                     'Healthy, mindful practices can help you recenter yourself when you need it most. Highmark''s dedicated Contemplation Nooks allow you to explore centering practices for physical and emotional rejuvenation.',
                     'essentials', TIMESTAMPTZ '2026-08-18 12:00:00-04'),
                    ('Highmark Interfaith Room',
                     'Visit the Interfaith Room in Highmark Center.',
                     'Practicing and exploring meaning-making is an important part of wellness and balance for many students. The Interfaith Room offers space to practice religion or spirituality or to gather with other for spiritual discussions, meetings, and reflection.',
                     'essentials', TIMESTAMPTZ '2026-08-18 12:00:00-04'),
                    ('CUC Prayer Room',
                     'Visit the Prayer Room in the Cohon University Center.',
                     'A multi-denominational prayer room is available 24 hours a day in the lower level of the Cohon University Center. The space features an ablution room with two private foot-washing stalls.',
                     'essentials', TIMESTAMPTZ '2026-08-18 12:00:00-04'),
                    ('Wright-Rogal Chapel',
                     'Visit the Wright-Rogal Chapel in the Cohon University Center.',
                     'Wright-Rogal Chapel is a prayer space on the first floor of the Cohon University Center. It features an auditorium-style set up for up to 35 people.',
                     'essentials', TIMESTAMPTZ '2026-08-18 12:00:00-04'),
                    ('Rest and Renewal',
                     'Rest, breathe, and relax with no agenda in the Mindfulness Room.',
                     'The Mindfulness Room is a dedicated space on campus to simply rest, breathe, and relax with no agenda. It is open 24 hours during the fall and spring semesters.',
                     'essentials', TIMESTAMPTZ '2026-08-18 12:00:00-04'),
                    ('Shuttle Stop',
                     'Find the CMU Shuttle Stop by Morewood Gardens!',
                     'CMU’s shuttles run on a fixed route with specific stops, starting as early as 7 a.m. for some routes and running into the evening. The university''s shuttles, as well as neighboring University of Pittsburgh''s shuttles, are available to faculty, staff and students, provided they have their CMU ID upon boarding.',
                     'essentials', TIMESTAMPTZ '2026-08-18 12:00:00-04'),
                    ('Color Printing Power: CFA',
                     'Find the Color Printer in College of Fine Arts Floor 3!',
                     'The Campus Printing service allows you to print from your computer or mobile phone to printers across campus. Send the file to the printer, then release the job at the printer by tapping your CMU ID. Central print release stations are available in computer labs, university libraries, some resident halls and public areas across campus. Some locations offer color printing, special paper sizes, scanning and copying. All students, faculty and staff are allotted a $40/semester print quota, which is associated with your CMU ID and debited when you release a print job at a campus printer. Computing Services also consults with departments to add departmental printers to the central print service.',
                     'essentials', TIMESTAMPTZ '2026-08-19 12:00:00-04'),
                    ('Bus Ride Guide',
                     'Check out the bus schedule at the digital Bus Sign in the University Center!',
                     'Developed and Funded in a joint effort between Undergraduate Student Senate and ScottyLabs, the CUC Bus Sign displays in real-time the upcoming PRT arrivals at the Forbes and Morewood bus stop.',
                     'essentials', TIMESTAMPTZ '2026-08-19 12:00:00-04'),
                    ('Bus Ride At Cohon University Center',
                     'Find the Bus Stop by the Cohon University Center!',
                     'During your time at CMU, if you pay the PRT fee for the semester, you can use the PRT Ready2Ride app to access bus rides via Allegheny County''s Pittsburgh Regional Transit. This includes the 28X line, which takes you to the Pittsburgh International Airport, as well as the 61A-D lines.',
                     'essentials', TIMESTAMPTZ '2026-08-19 12:00:00-04'),
                    ('Bus Ride On Morewood Avenue',
                     'Find the Bus Stop by Morewood Gardens!',
                     'During your time at CMU, if you pay the PRT fee for the semester, you can use the PRT Ready2Ride app to access bus rides via Allegheny County''s Pittsburgh Regional Transit. This includes the 28X line, which takes you to the Pittsburgh International Airport, as well as the 61A-D lines.',
                     'essentials', TIMESTAMPTZ '2026-08-19 12:00:00-04'),
                    ('Bus Ride On Margaret Morrison Street',
                     'Find the Bus Stop on Margaret Morrison Street!',
                     'During your time at CMU, if you pay the PRT fee for the semester, you can use the PRT Ready2Ride app to access bus rides via Allegheny County''s Pittsburgh Regional Transit. This includes the 28X line, which takes you to the Pittsburgh International Airport, as well as the 61A-D lines.',
                     'essentials', TIMESTAMPTZ '2026-08-19 12:00:00-04'),
                    ('Bus Ride on Fifth Avenue',
                     'Find the Bus Stop on Fifth Avenue!',
                     'During your time at CMU, if you pay the PRT fee for the semester, you can use the PRT Ready2Ride app to access bus rides via Allegheny County''s Pittsburgh Regional Transit. This includes the 28X line, which takes you to the Pittsburgh International Airport, as well as the 61A-D lines.',
                     'essentials', TIMESTAMPTZ '2026-08-19 12:00:00-04'),
                    ('Color Printing Power: Hunt Library',
                     'Find the Color Printer in Hunt Library Floor 1!',
                     'The Campus Printing service allows you to print from your computer or mobile phone to printers across campus. Send the file to the printer, then release the job at the printer by tapping your CMU ID. Central print release stations are available in computer labs, university libraries, some resident halls and public areas across campus. Some locations offer color printing, special paper sizes, scanning and copying. All students, faculty and staff are allotted a $40/semester print quota, which is associated with your CMU ID and debited when you release a print job at a campus printer. Computing Services also consults with departments to add departmental printers to the central print service.',
                     'essentials', TIMESTAMPTZ '2026-08-20 12:00:00-04'),
                    ('Job Hunters at the Advising Center',
                     'Explore careers and build your resume at the Career and Professional Development Center (CPDC) in the West Wing!',
                     'The Career and Professional Development Center (CPDC) is Carnegie Mellon University’s centralized career services center. They provide a comprehensive range of services, programs, and materials focusing on career exploration, professional development, experiential learning and employment assistance to meet the needs of evolving workplaces and your own goals in finding satisfying work!',
                     'essentials', TIMESTAMPTZ '2026-08-20 12:00:00-04'),
                    ('Job Hunters at the Interview Center',
                     'Practice for job interviews and attend workshops with the Career and Professional Development (CPDC) at the University Center!',
                     'The Career and Professional Development Center (CPDC) is Carnegie Mellon University’s centralized career services center. They provide a comprehensive range of services, programs, and materials focusing on career exploration, professional development, experiential learning and employment assistance to meet the needs of evolving workplaces and your own goals in finding satisfying work!',
                     'essentials', TIMESTAMPTZ '2026-08-20 12:00:00-04'),
                    ('Setting Up For Successful Studies',
                     'Check out the Student Academic Success Center for support in your coursework!',
                     'SASC provides course support in the form of supplemental instruction sessions, 1:1 tutoring, and drop-in tutoring; can help you build effective study techniques and skills; provide language support for multilingual learners; and much more. They also work with faculty and staff to improve coordination and professional development for your academic advisors. When your courses get tough, don''t be afraid to ask for help!',
                     'essentials', TIMESTAMPTZ '2026-08-20 12:00:00-04'),
                    ('Come On Down To Kirr Commons',
                     'Find Kirr Commons, in the Cohon University Center!',
                     'Kirr Commons, commonly referred to as the "UC Black Chairs," is the main lobby, student gathering space, and hub in the Cohon University Center. Events will also be held here throughout the year, such as Family Weekend photo-ops and the Kiltie Spring Carnival Concert.',
                     'cool_corners', TIMESTAMPTZ '2026-08-16 18:00:00-04'),
                    ('Let''s Go to Lee Commons',
                     'Find Lee Commons, in the Cohon University Center!',
                     'Lee Lobby, commonly referred to as the "UC Brown Chairs," serves as the grand entrance to the Cohon Center and as the new front door to Carnegie Mellon''s campus. Accentuated with natural light from floor to ceiling windows, the lobby is adorned with a spectacular Dale Chihuly glass sculpture, donated by board of trustees member Ed Frank and his wife Sarah Ratchye. Lee Lobby overlooks two beautiful rain gardens which nourish indigenous plants and vegetation.',
                     'cool_corners', TIMESTAMPTZ '2026-08-16 18:00:00-04'),
                    ('Won''t You Be My Neighbor?: Fifth Avenue Edition',
                     'Visit the Fifth Avenue Neightborhood Commons!',
                     'Located in the Fifth Avenue Neighborhood of campus, the Fifth Avenue Commons is a beautiful 5,000 square foot community space open to all Carnegie Mellon students, faculty and staff.',
                     'cool_corners', TIMESTAMPTZ '2026-08-16 18:00:00-04'),
                    ('Won''t Your Be My Neighbor?: Margaret Morrison Edition',
                     'Visit the Margaret Morrison Street Neighborhood Commons!',
                     'Located in the Margaret Morrison Street Neighborhood of campus, the Margaret Morrison Street Neighborhood Commons is a unique community space for all Carnegie Mellon students, faculty and staff to build community and connection.',
                     'cool_corners', TIMESTAMPTZ '2026-08-16 18:00:00-04'),
                    ('Defense! (It''s Over There!)',
                     'Check out The Fence!',
                     'The Fence is an iconic piece of Carnegie Mellon’s Pittsburgh campus. Serving as a student-centered space for free expression and community, The Fence has brought the CMU community together for more than a century. Governed by the Student Government Graffiti and Poster Policy, The Fence maintains specific expectations and rules regarding painting it (including only painting between midnight and sunrise, and only hand-painting). Adherence to the policy helps keep the tradition of The Fence alive for future Tartans.',
                     'cool_corners', TIMESTAMPTZ '2026-08-16 23:00:00-04'),
                    ('Paint Cleanup in Aisle Doherty',
                     'Check out the Doherty Fence Paint Cleanup Room!',
                     'Newly renovated and funded by the Student Senate, the Doherty Fence Paint Cleanup Room is where you''ll go to clean up your brushes (and very likely your hands) once you''re done painting the fence.',
                     'cool_corners', TIMESTAMPTZ '2026-08-16 23:00:00-04'),
                    ('Adventure In Andy''s Alcove',
                     'Check out Andy''s Alcove, in the CUC basement!',
                     'Named after CMU''s founder, Andy''s Alcove is a mixed-use space on the lower floor of the Cohon University Center between package pickup and Tartan Ink. The space offers plentiful seating as well as vending machines for food and beverages. The space may also be reserved for events.',
                     'cool_corners', TIMESTAMPTZ '2026-08-17 12:00:00-04'),
                    ('Game Start!',
                     'Play some games in the CUC Game Room!',
                     'Scotland Yard Game Room is a recreational space and game room located in the lower level of the Cohon University Center, featuring ping pong, pool, and foosball tables! Stop by and play some games with your friends.',
                     'cool_corners', TIMESTAMPTZ '2026-08-17 12:00:00-04'),
                    ('Counting On Kraus Campo',
                     'Take a trip to Kraus Campo (colloquially known as the Number Garden), on the roof of Posner Hall!',
                     'Rare among projects of this kind, the Number Garden (formally known as Kraus Campo) challenges the very definition of a garden: it is both garden-as-sculpture and sculpture-as-garden. Take some time to walk around or enjoy the weather.',
                     'cool_corners', TIMESTAMPTZ '2026-08-17 12:00:00-04'),
                    ('Searching For a Sorrells Study Spot',
                     'Find Sorrells Library, in Wean Hall!',
                     'The Roger Sorrells Engineering and Science Library, located on the fourth floor of Wean Hall, focuses on research support for the fields of computer science, engineering, mathematical sciences, physics and robotics, The library is named in honor of the late Roger Sorrells, thanks to a generous gift from his longtime partner, Dean emeritus of University Libraries Gloriana St. Clair. Read more about Roger Sorrells.',
                     'cool_corners', TIMESTAMPTZ '2026-08-17 12:00:00-04'),
                    ('Love, Love, Alumni',
                     'Visit the Alumni House!',
                     'Located just across the street from the University Center, the Alumni House stands as the hub for all Carnegie Mellon alumni programming, activities, and involvement. The first floor of the building is open to visitors during normal business hours every Monday through Friday. If you visit on Tuesdays with CMU Merch, you can participate in Tartan Tuesday!',
                     'cool_corners', TIMESTAMPTZ '2026-08-17 12:00:00-04'),
                    ('Feeling Generous?',
                     'Find the Giving Wall in CUC''s lower level, near the Postal Services'' Parcel pickup window!',
                     'Bring your unwanted, but still good items to our for others to use as new and pick up a few new-to-you items for yourself! Donate, take, or swap!',
                     'cool_corners', TIMESTAMPTZ '2026-08-17 12:00:00-04'),
                    ('Fitness Fiend: CUC Edition',
                     'Work out at the Fitness Center in the Cohon University Center!',
                     'The Cohon University Center''s Fitness Center offers two floors dedicated to cardio and weight equipment, including more than 60 cardio machines, selectorized and Olympic weight equipment, and free weights. There are also specific areas and spaces for assessment, stretching, and personal training. The space is designed to accommodate all types of workout styles and preferences, with personal viewing monitors, TV screens, and large floor to celing windows overlooking Forbes Avenue.',
                     'cool_corners', TIMESTAMPTZ '2026-08-18 12:00:00-04'),
                    ('Fitness Fiend: Tepper Edition',
                     'Work out at the Fitness Center in Tepper School of Business!',
                     'At the Tepper Fitness Center, you can exercise with treadmills, bikes, weights and more. You can also check out equipment such as jump ropes and resistance tubes, and purchase personal training sessions. The Fitness Center also has an ourdoor terrace area overlooking Fifth Avenue.',
                     'cool_corners', TIMESTAMPTZ '2026-08-18 12:00:00-04'),
                    ('Planting A Peace Of Mind',
                     'Take a breather at the Peace Garden outside of Hunt Library!',
                     'The Peace Garden is an initiative that encompasses both architectural innovation and sustainable design. It aims to enhance the quality of life on campus by transforming a virtual design into a tangible, functional space for the CMU community.',
                     'cool_corners', TIMESTAMPTZ '2026-08-19 12:00:00-04'),
                    ('TechSpark Tour',
                     'Get creative at the TechSpark makerspace, located in Hammerschlag Hall!',
                     'TechSpark is Carnegie Mellon University’s focal point for technology innovation. This facility provides equipment for rapidly prototyping designs from ideas to reality for educational, extracurricular, and research activities. It is a hands-on learning and exploration space available for current College of Engineering students, faculty, staff, and collaborators across campus (though in order to use any equipment, you must first take its corresponding course).',
                     'cool_corners', TIMESTAMPTZ '2026-08-19 12:00:00-04'),
                    ('Tartan Collaborative Commons',
                     'Visit the Tartan Collaborative Commons!',
                     'Designed and funded by the Undergraduate Student Senate, the Tartan Collaborative Commons features a variety of seating configurations and work zones, as well as whiteboards and power outlets throughout the room to create a collaborative working environment. The space has two six-person free-standing conference rooms equipped with TV screens and whiteboard walls, as well as a professional headshot booth.',
                     'cool_corners', TIMESTAMPTZ '2026-08-20 12:00:00-04'),
                    ('Wean 1 Lower Entrance',
                     'Find the entrance to the first floor Wean Hall!',
                     'Not many students know about the lower entrance to Wean Hall, or the parking lot around it. But it makes for a great shortcut when travelling between classes!',
                     'cool_corners', TIMESTAMPTZ '2026-08-20 12:00:00-04'),
                    ('Hunting For A Study Spot',
                     'Find Hunt Library!',
                     'Hunt Library is the largest library on campus, housing four floors of volumes comprising the university''s collections in the arts, humanities, and social science. Special Collections, University Archives, and the video collection are located in Hunt Library. The fifth floor is home to the Hunt Institute for Botanical Documentation, which specializes in the history of botany and all aspects of plant science. The university''s IDeATe program, which offers nine undergraduate minors in domains that merge technology and arts expertise, is housed in the basement. The building opened in 1961, thanks to the generosity of Mr. and Mrs. Roy Hunt.',
                     'cool_corners', TIMESTAMPTZ '2026-08-20 12:00:00-04'),
                    ('Student Orgs Abound',
                     'Visit CUC 303, where many student organizations meet!',
                     'CUC 303 is the meeting area of many clubs and student organizations at CMU. If you student org is given access to the space, you can use the binder inside to reserve time for the room.',
                     'cool_corners', TIMESTAMPTZ '2026-08-20 12:00:00-04'),
                    ('Frame It On Forbes',
                     'Check out The Frame, CMU''s student-run art gallery!',
                     'The Frame Gallery is a non-profit, student-run art space, committed to showcasing the artistic work of Carnegie Mellon students, promoting ambitious and experimental art within the community.',
                     'cool_corners', TIMESTAMPTZ '2026-08-20 12:00:00-04'),
                    ('Don''t Feel Two-Tired!',
                     'Check out Tartan Bike Project, CMU''s student-led campus bike shop!',
                     'The Tartan Bike Project (TBP) offers all you need to get going on a bicycle. Stop in to get advice on bike repair and maintenance, or sign up for a repair appointment. If you don’t yet have a bike, TBP offer short and long-term rentals and affordable used-bike sales. TBP is also a hub for social bike rides, campus bike events and bike-related activism.',
                     'cool_corners', TIMESTAMPTZ '2026-08-20 12:00:00-04'),
                    ('Pausch Bridge',
                     'Take a trip down Pausch Bridge, connecting Gates-Hillman Center and Purnell Center For the Arts!',
                     'Pausch Bridge connects one of the university’s fine arts buildings, Purnell Center, with the Gates & Hillman Centers, the home for computer science at Carnegie Mellon. The bridge features more than 7,000 programmable (and environmentally friendly) LED lights, and each segment even has a hidden penguin! In the Spring, CMU offers "62-661: Interaction and Expression using Pausch Bridge Lighting" if you want the chance to create your own light show.',
                     'bridges', TIMESTAMPTZ '2026-08-17 12:00:00-04'),
                    ('Gates 4 <—> NSH 4',
                     'Take a walk down the bridge between Gates-Hillman Center 4 and Newell Simon Hall 4!',
                     'Did you know that you can travel between Wean, Gates, Newell-Simon Hall, and more, all without stepping outside? These pathways are perfect for when the Pittsburgh weather gets a bit too intense, so try finding all of the connections!',
                     'bridges', TIMESTAMPTZ '2026-08-17 12:00:00-04'),
                    ('NSH 4 <—> Wean 4',
                     'Take a walk down the bridge between Newell-Simon Hall 4 and Wean Hall 4!',
                     'Did you know that you can travel between Wean, Gates, Newell-Simon Hall, and more, all without stepping outside? These pathways are perfect for when the Pittsburgh weather gets a bit too intense, so try finding all of the connections!',
                     'bridges', TIMESTAMPTZ '2026-08-17 12:00:00-04'),
                    ('Doherty B <—> Wean 4',
                     'Find the pathway between Doherty Hall B and Wean Hall 4!',
                     'Did you know that you can travel between Wean, Doherty, Gates, and more, all without stepping outside? These pathways are perfect for when the Pittsburgh weather gets a bit too intense, so try finding all of the connections!',
                     'bridges', TIMESTAMPTZ '2026-08-17 12:00:00-04'),
                    ('Wean Hall 4 <—> Scott Hall 4',
                     'Take a walk down the pathway between Wean Hall 4 and Scott Hall 4!',
                     'Did you know that you can travel between Wean, Scott Hall, Hamerschlag Hall, and more, all without stepping outside? These pathways are perfect for when the Pittsburgh weather gets a bit too intense, so try finding all of the connections!',
                     'bridges', TIMESTAMPTZ '2026-08-18 12:00:00-04'),
                    ('Scott Hall 4 <—> Hamerschlag Hall C',
                     'Check out the pathway between Scott Hall 4 and Hammerschlag Hall C!',
                     'Did you know that you can travel between Wean, Scott Hall, Hamerschlag Hall, and more, all without stepping outside? These pathways are perfect for when the Pittsburgh weather gets a bit too intense, so try finding all of the connections!',
                     'bridges', TIMESTAMPTZ '2026-08-18 12:00:00-04'),
                    ('Hamerschlag Hall C <—> Ansys Hall C',
                     'Find the connection between Hammerschlag Hall C and Ansys Hall C!',
                     'Did you know that you can travel between Scott Hall, Hamerschlag Hall, Ansys Hall, and more, all without stepping outside? These pathways are perfect for when the Pittsburgh weather gets a bit too intense, so try finding all of the connections!',
                     'bridges', TIMESTAMPTZ '2026-08-18 12:00:00-04'),
                    ('Ansys Hall A <—> Porter Hall A',
                     'Check out the pathway between Ansys Hall A and Porter Hall A!',
                     'Did you know that you can travel between Ansys Hall, Porter Hall, Baker Hall, and more, all without stepping outside? These pathways are perfect for when the Pittsburgh weather gets a bit too intense, so try finding all of the connections!',
                     'bridges', TIMESTAMPTZ '2026-08-18 12:00:00-04'),
                    ('Doherty Hall A <—> Wean Hall 5',
                     'Find the pathway between Doherty Hall A and Wean Hall 5!',
                     'Did you know that you can travel between Wean, Doherty, Scott Hall, and more, all without stepping outside? These pathways are perfect for when the Pittsburgh weather gets a bit too intense, so try finding all of the connections!',
                     'bridges', TIMESTAMPTZ '2026-08-19 12:00:00-04'),
                    ('Friends of Engineering Bridge',
                     'Go for a walk on the Friends of Engineering Bridge, located between Ansys Hall and Scott Hall!',
                     'This high-traffic corridor connects the upper campus with the engineering quad. As you cross the Friends of Engineering Bridge, you’ll see a striking juxtaposition: legacy on one side, in the form of nameplate plaques honoring the Engineering community and their mentors; and the future on the other, with a view directly into the B and C levels of ANSYS Hall of students working on innovative, hands-on projects in TechSpark.',
                     'bridges', TIMESTAMPTZ '2026-08-19 12:00:00-04'),
                    ('Doherty 1 <—> Wean 6',
                     'Find the pathway between Doherty Hall 1 and Wean Hall 6!',
                     'Did you know that you can travel between Wean, Doherty, Gates, and more, all without stepping outside? These pathways are perfect for when the Pittsburgh weather gets a bit too intense, so try finding all of the connections!',
                     'bridges', TIMESTAMPTZ '2026-08-19 12:00:00-04'),
                    ('Doherty 2 <—>Wean 7',
                     'Find the pathway between Doherty Hall 2 and Wean Hall 7!',
                     'Did you know that you can travel between Wean, Doherty, Scott Hall, and more, all without stepping outside? These pathways are perfect for when the Pittsburgh weather gets a bit too intense, so try finding all of the connections!',
                     'bridges', TIMESTAMPTZ '2026-08-20 12:00:00-04'),
                    ('Doherty 2 <—>Wean 8',
                     'Find the pathway between Doherty Hall 2 and Wean Hall 8!',
                     'Did you know that you can travel between Wean, Doherty, Gates, and more, all without stepping outside? These pathways are perfect for when the Pittsburgh weather gets a bit too intense, so try finding all of the connections!',
                     'bridges', TIMESTAMPTZ '2026-08-20 12:00:00-04'),
                    ('Doherty 3 <—>Wean 8',
                     'Find the pathway between Doherty Hall 3 and Wean Hall 8!',
                     'Did you know that you can travel between Wean, Doherty, Gates, and more, all without stepping outside? These pathways are perfect for when the Pittsburgh weather gets a bit too intense, so try finding all of the connections!',
                     'bridges', TIMESTAMPTZ '2026-08-20 12:00:00-04'),
                    ('Party At The CMU Pantry',
                     'Check out the CMU Pantry in Residence on Fifth!',
                     'The CMU Pantry is a free, supplemental food resource open to all undergraduate and graduate students. Shoppers are able to visit the Pantry once a week. The Pantry provides shoppers access to meats, fruits, vegetables, and frozen ready-to-eat meals based on availability. Additionally, there is a consistent stock of non-perishables including staple items such as pasta, rice, peanut butter, and canned goods. The Pantry also stocks toiletry and personal hygiene items.',
                     'lets_eat', TIMESTAMPTZ '2026-08-16 18:00:00-04'),
                    ('A Bite of Au Bon Pain',
                     'Grab a sandwich at Au Bon Pain!',
                     'At Au Bon Pain café bakery, each signature recipe is uniquely crafted. You can enjoy delicious hot or iced coffee and teas, espresso drinks, a variety of cold beverages, soup, a customized made-to-order breakfast or lunch sandwich or salad, or you can grab a pre-made salad, sandwich, wrap, yogurt parfait, fresh fruit or snack. There is always something new to try, from nutritious foods and healthy choices, to comfort food and indulgent treats!',
                     'lets_eat', TIMESTAMPTZ '2026-08-21 12:00:00-04'),
                    ('Build Pizza to Perfection',
                     'Get some brick-oven pizza at Build Pizza in Tepper!',
                     'Brick oven-baked flatbread pizza take the stage at BUILD. When you go to BUILD Pizza, you''ll find three choices every day: classic cheese, traditional pepperoni, and a chef-driven special.',
                     'lets_eat', TIMESTAMPTZ '2026-08-21 12:00:00-04'),
                    ('Chowing Down On Ciao Bella',
                     'Build your own pasta bowl at Ciao Bella!',
                     'Ciao Bella takes a globally inspired approach to pasta. Discover a menu of traditional dishes featuring international flavors, as well as customizable pasta bowls.',
                     'lets_eat', TIMESTAMPTZ '2026-08-21 12:00:00-04'),
                    ('Chomping On Crisp and Crust',
                     'Have a salad or flatbread at Crisp and Crust!',
                     'Crisp and Crust is a greens-driven location that takes salads and flatbreads to a new level, boasting a fully customizable menu along with some delicious signature dishes. The "build-your-own" menu will highlight ingredients like burrata and edamame, while "signatures" feature classics like the Caesar salad or Margherita Flatbread, as well as unique-to-CMU items like the Thai Crunch salad and Philly Cheesesteak Roll-up.',
                     'lets_eat', TIMESTAMPTZ '2026-08-21 12:00:00-04'),
                    ('Deliciously De Fer',
                     'Grab some coffee at De Fer in Hunt Library!',
                     'De Fer Coffee & Tea serves locally-roasted specialty coffee, tea, and scratch-made food in the Maggie Murph Café in Hunt Library. Locally owned and operated by CMU alum, Atelier de Fer has been roasting coffee at its flagship store in Pittsburgh’s Strip District since 2017. In addition to a full coffee/tea menu, you can get house-made scones, muffins, cookies, paninis, smoothies and parfaits.',
                     'lets_eat', TIMESTAMPTZ '2026-08-21 12:00:00-04'),
                    ('The Edge of Greatness',
                     'Have some kosher pizza and bagels at The Edge Cafe & Market in Resnik!',
                     'The Edge is a Vaad-certified kosher cafe and market. Here, you''ll find freshly baked bagels, bagel sandwiches, Turkish bourekas, wraps, salads, pasta, and artisan pizzas baked in our hearthstone oven. It is located in Tartans Pavilion, overlooking Gesling Stadium.',
                     'lets_eat', TIMESTAMPTZ '2026-08-21 12:00:00-04'),
                    ('Sweet Tooth For Sweet Plantain',
                     'Enjoy Cuban-styled cuisine at Sweet Plantain!',
                     'Sweet Plantain is a Cuban-inspired dining location featuring bold, traditional flavors. Enjoy Ropa Vieja, tender shredded beef in a rich tomato sauce, or Fricase de Pollo, creamy chicken stew—both served with yellow rice, black beans, and sweet plantains. The Picadillo a la Habanera blends ground beef, potatoes, raisins, olives, and capers for a savory-sweet delight, while the Vegetarian Bowl offers yuca, plantains, and Cuban staples. The Cubano-Style Sandwich combines turkey bacon, avocado, pickles, and zesty condiments in a crispy press. Sides include tangy Yuca con Mojo, sweet Platano Maduro Frito, and flavorful Arroz Amarillo con Frijoles.',
                     'lets_eat', TIMESTAMPTZ '2026-08-21 12:00:00-04'),
                    ('Enter: Entropy+',
                     'Grab some snacks and groceries at Entropy+!',
                     'Entropy+ is the on-campus go-to spot for grocery items, health and beauty aids, bottled beverages, snacks, sweets, and local foods. In addition to their convenience products, you can find a variety of grab-and-go meals: find hot and cold from our allergen-friendly kitchen Nourish, fresh-made sandwiches, salads, sushi, fresh fruits and veggies, and more.',
                     'lets_eat', TIMESTAMPTZ '2026-08-21 12:00:00-04'),
                    ('Eating Up The Exchange',
                     'Get a sandwich at The Exchange in Posner Hall!',
                     'The Exchange offers custom deli sandwiches, soups, hot entrées, fresh baked goods, fruit, yogurt parfaits, snack and energy bars, and other grab-and-go items. The designated coffee bar includes hot brewed La Prima coffee, specialty and organic teas, cold beverages, and bottled juices.',
                     'lets_eat', TIMESTAMPTZ '2026-08-21 12:00:00-04'),
                    ('Flameo, Fire and Stone',
                     'Get some steaks, fish, and wings at Fire and Stone in Resnik!',
                     'Fire and Stone is a great new location featuring fresh steaks, fish, sandwiches, and wings.',
                     'lets_eat', TIMESTAMPTZ '2026-08-21 12:00:00-04'),
                    ('Feasting On Forbes Avenue Subs',
                     'Check out Forbes Avenue Subs in Tepper!',
                     'Build your perfect sub or wrap at Forbes Avenue Subs, a deli-style eatery featuring fresh-sliced deli meat and cheeses.',
                     'lets_eat', TIMESTAMPTZ '2026-08-21 12:00:00-04'),
                    ('Hungry For Some Hunan',
                     'Grab some Chinese cuisine at Hunan Express in Newell-Simon Hall!',
                     'Authentic Chinese cuisine, featuring sauces made with bone broth. Choose your base of noodles or rice and build your own meal with General Tso’s chicken, stir fry tofu, seasonal vegetables, or pork ribs in black bean sauce. Braised fish, spring rolls, pork dumplings, red bean rice cakes are also available daily. For dessert, enjoy fruit smoothies and build-your-own milk or fruit boba tea, with bubble toppings like tapioca, rainbow jelly, lychee jelly and popping boba.',
                     'lets_eat', TIMESTAMPTZ '2026-08-21 12:00:00-04'),
                    ('Grabbing Some Gates La Prima',
                     'Grab some coffee at La Prima in Gates-Hillman Center!',
                     'La Prima Espresso Company is a Pittsburgh-based certified organic roaster offering exceptional Italian-style coffee and espresso, cold brew, nitro, chai and matcha green tea lattes, frizz coffee, and more. You can pick up made-daily pastries, grab-and-go sandwiches, and vegetarian meals, and order hot sandwiches are for breakfast and lunch.',
                     'lets_eat', TIMESTAMPTZ '2026-08-21 12:00:00-04'),
                    ('Want Some Wean La Prima',
                     'Grab some coffee at La Prima in Wean Hall!',
                     'La Prima Espresso Company is a Pittsburgh-based certified organic roaster offering exceptional Italian-style coffee and espresso, cold brew, nitro, chai and matcha green tea lattes, frizz coffee, and more. You can pick up made-daily pastries, grab-and-go sandwiches, and vegetarian meals, and order hot sandwiches are for breakfast and lunch.',
                     'lets_eat', TIMESTAMPTZ '2026-08-21 12:00:00-04'),
                    ('Craving Mille''s Ice Cream',
                     'Have some ice cream at Millie''s Coffee ''n'' Creamery in Tepper!',
                     'Pittsburgh-based Millie''s Homemade Ice Cream is now scooping at CMU! Millie''s Coffee ''n'' Creamery serves chef-inspired ice creams, vegan gelatos, KLVN coffee and espresso drinks, Goodlander draft tea, and artisan pastries. Perfect for breakfast-on-the-go, an after-dinner sweet treat, or anything in between. FLEX dollars and DineXtra are accepted as well!',
                     'lets_eat', TIMESTAMPTZ '2026-08-21 12:00:00-04'),
                    ('Nourish-ing Noms',
                     'Have some allergen friendly dining at Nourish!',
                     'Nourish is an allergen-friendly kitchen with a menu prepared without gluten, wheat, milk, sesame, egg, soy, fish, shellfish, peanuts, and most tree nuts (except coconut). In addition to offering a diverse and delicious menu designed with everyone in mind, Nourish serves safe foods for their guests with dietary restrictions. Grab-and-go items from Nourish are available at Entropy+, Rothberg’s Roasters II, and Tepper Eatery. Items can be purchased individually or as a block meal on your meal plan.',
                     'lets_eat', TIMESTAMPTZ '2026-08-21 12:00:00-04'),
                    ('Aloha, Ola Ola',
                     'Grab a Hawaiian Bowl at Ola Ola in the Cohon University Center!',
                     'Bringing island vibes to CMU, Ola Ola Bowls serves up bold, Hawaiian-inspired flavors with a modern twist. Build your perfect Loco Moco Bowl starting with fluffy white rice, your choice of protein like Marinated Tofu Steak, Huli Huli Chicken, or a Halal Burger Patty. Then load up with vibrant toppings like kimchi, scallions, radish, and crunchy wonton strips! They also serve Spam Musubi, indulgent Portuguese desserts, and cool, refreshing tropical drinks.',
                     'lets_eat', TIMESTAMPTZ '2026-08-21 12:00:00-04'),
                    ('Ready For Redhawk',
                     'Check out Redhawk Coffee in Scaife Hall!',
                     'Redhawk Coffee is a local, family-owned coffee roasting company dedicated to serving the best specialty coffee on the market. With an approachable roast style and a variety of drinks, Redhawk will have plenty of options for you. Try one of their fresh baked pastries from Driftwood Oven or even a matcha latte made with ceremonial grade matcha tea. Other popular options include mochas with Brunton’s chocolate milk and our signature honey-cinnamon latte.',
                     'lets_eat', TIMESTAMPTZ '2026-08-21 12:00:00-04'),
                    ('Revin'' Up For Rev Noodle',
                     'Grab a custom-made Malatang Bowl at Revolution Noodle in the Cohon University Center!',
                     'From the creators of Hunan Express comes Revolution Noodle! Build your perfect Malatang noodle bowl with house-made broths, fresh noodles, seasonal vegetables, and various proteins. Don’t forget to add a savory bao bun, bubble tea, or fruit smoothie.',
                     'lets_eat', TIMESTAMPTZ '2026-08-21 12:00:00-04'),
                    ('Sharing Some Schatz',
                     'Check out Schatz Dining in the Cohon University Center for some all-you-can-eat dining!',
                     'Schatz Dining is an all-you-can-eat buffet on the second floor of the Cohon University Center, with a rotating menu. One meal block gets you access to Schatz for an entire meal period, so eat as much as like!',
                     'lets_eat', TIMESTAMPTZ '2026-08-21 12:00:00-04'),
                    ('Scotty''s Market Mania',
                     'Get some groceries and Mediterranean food at Scotty''s Market!',
                     'Operated by locally-owned Salem’s Market and Grill, who started their business 40 years ago in the heart of Oakland, Scotty’s Market is stocked with fresh produce, drinks, snacks, and international and conventional grocery items. The Grill at Scotty’s Market offers a wide selection of savory Mediterranean fare, including beef and lamb gyros, curries, sides, and breakfast sandwiches. Scotty''s Market is closed on Fridays from 1-2pm for prayer.',
                     'lets_eat', TIMESTAMPTZ '2026-08-21 12:00:00-04'),
                    ('Shake Smarter, Not Harder',
                     'Check out Shake Smart in Highmark Center for some protein shakes and acai bowls!',
                     'Shake Smart is a nutritious, health-forward smoothie and acai bowl location. Their wide-ranging menu includes a mix of protein-packed shakes, fruit-forward smoothies, acai bowls, and more.',
                     'lets_eat', TIMESTAMPTZ '2026-08-21 12:00:00-04'),
                    ('Super Stack''d Underground',
                     'Grab a burger, some chicken, or a grilled cheese sandwich at Stack''d Underground!',
                     'Stack''d Underground combines signature dishes from the popular restaurants in Oakland. The menu includes smash’d burgers from Stack’d, Nashville chicken from CHiKN, and gourmet grilled cheese from Melt’d. In addition the location offers a selection of wraps, salads as well as a variety of vegetarian and halal options. There''s also a dessert bar, where you can get made-to-order milkshakes, sundaes, floats, banana splits and more.',
                     'lets_eat', TIMESTAMPTZ '2026-08-21 12:00:00-04'),
                    ('Need Me Some Tahini',
                     'Get some Mediterranean food at Tahini!',
                     'Tahini by Elegant Edge serves fresh, authentic Mediterranean cuisine, certified kosher by the Vaad Harabonim of Greater Pittsburgh. The menu features shawarma, vegan eggplant shawarma, falafel pita sandwiches, couscous and hummus bowls, freshly prepared sides including grape leaves, Israeli chopped salad, and zahtar pita fries. Offerings include a variety of plant-based and vegan options.',
                     'lets_eat', TIMESTAMPTZ '2026-08-21 12:00:00-04'),
                    ('Tasty Taste of India',
                     'Grab some Indian food at Taste of India in Resnik!',
                     'Taste of India offers a diverse menu featuring a variety of flavorful dishes from various regions of India. Expect aromatic spices, rich curries, tandoori specialties, and a range of vegetarian and non-vegetarian options. Whether you''re a fan of samosas, chicken curry, tandori chicken or butter chicken, Taste of India provide a vibrant tastes of India.',
                     'lets_eat', TIMESTAMPTZ '2026-08-21 12:00:00-04'),
                    ('Talking About Tepper Taqueria',
                     'Grab some street-style tacos at Tepper Taqueria!',
                     'Traditional, street-style tacos take the stage at Tepper Taqueria. Choose your style (taco, burrito, bowl, or nachos) from the make-your-own menu, and fill it with your choice of house-marinated meats (including a vegetarian, plant-based beef), rice and beans, and delicious, classic toppings.',
                     'lets_eat', TIMESTAMPTZ '2026-08-21 12:00:00-04'),
                    ('World of Wild Blue',
                     'Check out Wild Blue Sushi in Scott Hall!',
                     'Wild Blue Sushi crafts fresh sushi daily using sustainably sourced seafood, made-to-order rice bowls and bubble teas. You can select from a wide variety of grab-and-options or request custom sushi, prepared on the spot. From rainbow rolls and poke bowls to orange chicken and tofu rice bowls, Wild Blue has something for sushi lovers and more.',
                     'lets_eat', TIMESTAMPTZ '2026-08-21 12:00:00-04'),
                    ('Zoomin'' On Over To Zebra Lounge',
                     'Grab some kosher and Halal meals and pastries at Zebra Lounge!',
                     'Nestled within the Great Hall of the College of Fine Arts is the trendy coffeehouse Zebra Lounge, offering a diverse selection of treats. Zebra Lounge brews locally roasted hot and cold Mechanic coffee and espresso drinks, teas, and cold beverages. Explore their wide selection of Vaad-certified kosher and Halal meals, including freshly baked pastries, hearthstone pizza, grab-and-go sandwiches and sushi, and a bagel bar, where you can choose from cream cheese, lox, and fresh vegetables. Zebra Lounge is ideal for starting your day with a delightful breakfast, enjoying a satisfying lunch, delving into an afternoon of focused study, or showcasing your artistic abilities, whether through song, music, or theater.',
                     'lets_eat', TIMESTAMPTZ '2026-08-21 12:00:00-04'),
                    ('CFA: All The Campus Is A Stage',
                     'Check out Purnell Center for the Arts!',
                     'Purnell Center for the Arts houses School of Drama’s state-of-the-art performance spaces, design studios, and classrooms. Throughout the year, School of Drama students hold many performances, including the signature winter showcase "Playground," featuring many student-original short performances.',
                     'minor_major_general', TIMESTAMPTZ '2026-08-19 12:00:00-04'),
                    ('TSB: Breakout Room 2',
                     'Visit the Tepper Breakout Room on the second floor!',
                     'There are six breakout spaces dedicated to undergraduate students and 12 dedicated to master’s students. Tepper Students have 24/7 access to these rooms; other students can reserve this space on 25Live.',
                     'minor_major_general', TIMESTAMPTZ '2026-08-19 12:00:00-04'),
                    ('SCS: I Can See My Dorm From Here!',
                     'Check out the view on the GHC 6 Balcony!',
                     'The Gates Floor 6 Balcony gives you a great view of Forbes Avenue, Tepper, and Smith Hall, and more. SCS students have 24/7 accessto Gates-Hillman Center.',
                     'minor_major_general', TIMESTAMPTZ '2026-08-19 12:00:00-04'),
                    ('CIT: Lounge Days',
                     'Hang out in the ECE Undergraduate Lounge!',
                     'Located in Hamerschlag Hall is an Undergraduate Lounge dedicated to ECE students.',
                     'minor_major_general', TIMESTAMPTZ '2026-08-19 12:00:00-04'),
                    ('DC: Baking Arts In Baker Hall',
                     'Visit Baker Hall, the home of Dietrich College!',
                     'Baker Hall is home to Dietrich College of Humanities and Social Sciences. Dietrich contains 11 different departments, each with over half a dozen undergraduate and graduate degrees.',
                     'minor_major_general', TIMESTAMPTZ '2026-08-19 12:00:00-04'),
                    ('MCS: Lounge Days (Bio Edition)',
                     'Relax in the Bio Lounge, located in Doherty Hall!',
                     'Housed within the Mellon College of Science, the Biological Sciences department provides students with rigorous training in Biology, while building a strong foundation in all of the natural sciences. Doherty Hall is the home of Biological Sciences, including labs and their lounge.',
                     'minor_major_general', TIMESTAMPTZ '2026-08-19 12:00:00-04'),
                    ('CFA: World Architects',
                     'Check out the Architecture Studio!',
                     'School of Architecture has two dedicated studios: CFA 200 and the Intelligent Workspace (MM 312). Here, SoA students learn about the discipline of architecture, intensified by the broader Carnegie Mellon culture of interdisciplinary innovation and creative inquiry.',
                     'minor_major_general', TIMESTAMPTZ '2026-08-20 12:00:00-04'),
                    ('TSB: Breakout Room 3',
                     'Visit the Tepper Breakout Room on the third floor!',
                     'There are six breakout spaces dedicated to undergraduate students and 12 dedicated to master’s students. Tepper Students have 24/7 access to these rooms; other students can reserve this space on 25Live.',
                     'minor_major_general', TIMESTAMPTZ '2026-08-20 12:00:00-04'),
                    ('SCS: Gates Courtyard',
                     'Relax at the courtyard outside GHC 3!',
                     'Below Pausch Bridge lies the Gates-Hillman Center courtyard, with chairs and a volleyball court. This is where, among other events, the SCS end-of-year picnic is held. If you''re lucky, you may even see goats grazing on the hill!',
                     'minor_major_general', TIMESTAMPTZ '2026-08-20 12:00:00-04'),
                    ('CIT: CivE Labbing',
                     'Experiment in the CivE Lab in Porter Hall!',
                     'Located in Port Hall is an Undergraduate Lounge dedicated to Civil Engineering students.',
                     'minor_major_general', TIMESTAMPTZ '2026-08-20 12:00:00-04'),
                    ('MCS: Lounge Days (Chemistry Edition)',
                     'Take a break in the Chemistry Lounge, located in Doherty Hall!',
                     'Chemistry majors at CMU learn cutting-edge chemistry in a highly supportive environment with outstanding faculty and superb facilities in both Doherty Hall and Mellon Institute. There are a variety of degree programs to pursue, as well as plenty of research opportunities for these students.',
                     'minor_major_general', TIMESTAMPTZ '2026-08-20 12:00:00-04'),
                    ('Heinz: Home Sweet Hamburg',
                     'Visit Hamburg Hall, the home of Heinz College!',
                     'Heinz College is the home of "data-centered social sciences," housing the Undergraduate Information Systems major, the Decision Analytics & Systems minor, and over a dozen master''s programs.',
                     'minor_major_general', TIMESTAMPTZ '2026-08-20 12:00:00-04'),
                    ('DC: Baker Hall Green Roof',
                     'Head to the Green Roof of Baker Hall!',
                     'Baker Hall was renovated to add the Adamson Wing in 2018. By expanding the building’s underground footprint, space was created above allowing for a green roof garden. Disguised at ground level, the green space outside of Baker Hall functions as a green roof for a below-ground portion of the building. The “roof” features landscaped areas, a brick walking path, and skylights where one can peer into the study space below.',
                     'minor_major_general', TIMESTAMPTZ '2026-08-20 12:00:00-04'),
                    ('Integrated Artists',
                     'Explore the facilities and resources of the IDeATe department, located in the Hunt Library basement!',
                     'The Integrative Design, Arts, and Technology (or IDeATe) network is housed in the Hunt Library basement. The program offers dozens of undergraduate courses and nine undergraduate minors, including Game Design, Animation & Special Effects, and Immersive Technologies in Arts & Culture. IDeATe merges technology and creativity to provide learning opportunities for interdisciplinary collaboration. IDeATe minors and courses are open to all majors, and they welcome students from every discipline to their unique learning environment.',
                     'minor_major_general', TIMESTAMPTZ '2026-08-21 12:00:00-04'),
                    ('CFA: Without Music Rooms, Life Would B Flat',
                     'Practice some music in the CFA practice rooms!',
                     'Student practice rooms are located on the mezzanine floor of the College of Fine Arts, containing pianos and music stands. School of Music students have 24/7 access to these rooms.',
                     'minor_major_general', TIMESTAMPTZ '2026-08-21 12:00:00-04'),
                    ('TSB: Starting Up',
                     'Visit the Schwartz Center For Entrepreneuership in Tepper!',
                     'The hub of entrepreneurship at Carnegie Mellon is the Swartz Center for Entrepreneurship — located within the Tepper Quad — a campus-wide center for innovation that brings together business, technology, and design. Deeply collaborative and extraordinarily supportive, the center’s success stories range from tech to health care to energy. Duolingo, Wigle Whiskey, and Fifth Season are just a few.',
                     'minor_major_general', TIMESTAMPTZ '2026-08-21 12:00:00-04'),
                    ('SCS: Render Time',
                     'Visit the Graphics Lounge in Smith Hall!',
                     'The Carnegie Mellon Graphics Lab conducts cutting-edge research on computer graphics and computer vision, integrating insights from computer science, robotics, and mechanical engineering.',
                     'minor_major_general', TIMESTAMPTZ '2026-08-21 12:00:00-04'),
                    ('CIT: MechE Madness',
                     'CIT: MechE Madness',
                     'Mechanical Engineering (MechE) students and their classes will most often be found in Scaife Hall.',
                     'minor_major_general', TIMESTAMPTZ '2026-08-21 12:00:00-04'),
                    ('DC: Lounge Days',
                     'Visit the Dietrich Lounge, located in Baker Hall!',
                     'The Dietrich Lounge is located in the Dietrich College Dean''s Office. You can reserve the lounge (and other DC Dean''s Office spaces) by contacting hssrooms@andrew.cmu.edu.',
                     'minor_major_general', TIMESTAMPTZ '2026-08-21 12:00:00-04'),
                    ('MCS: Lounge Days (Physics Edition)',
                     'Rest up in the Physics Lounge, located in Doherty Hall!',
                     'The Physics Department at Carnegie Mellon University offers a broad range of options for undergraduates, a strong graduate program, and cutting-edge research. While the Physics Department is largely found in Wean Hall and Hunt Library, the Physics lounge is located in Doherty Hall.',
                     'minor_major_general', TIMESTAMPTZ '2026-08-21 12:00:00-04'),
                    ('How Hot? Red Hot! (Boss and McGill Edition)',
                     'Start your adventure (or visit a friend) at the Boss and McGill (BaM) courtyard!',
                     'During Orientation Week, tap your mobile device at an O-Quest Challenge Point to complete a Challenge and earn ScottyCoins!',
                     'residence_relaxation', TIMESTAMPTZ '2026-08-16 18:00:00-04'),
                    ('Let''s Go, WHeSco!',
                     'Start your adventure (or visit a friend) at the Welsch, Henderson, and Scobell courtyard!',
                     'During Orientation Week, tap your mobile device at an O-Quest Challenge Point to complete a Challenge and earn ScottyCoins!',
                     'residence_relaxation', TIMESTAMPTZ '2026-08-16 18:00:00-04'),
                    ('Yeah, Donner!',
                     'Start your adventure (or visit a friend) in front of Donner House!',
                     'During Orientation Week, tap your mobile device at an O-Quest Challenge Point to complete a Challenge and earn ScottyCoins!',
                     'residence_relaxation', TIMESTAMPTZ '2026-08-16 18:00:00-04'),
                    ('Morewood/E-Tower Power!',
                     'Start your adventure (or visit a friend) in the Morewood Lobby, home of Morewood Gardens and E-Tower!',
                     'During Orientation Week, tap your mobile device at an O-Quest Challenge Point to complete a Challenge and earn ScottyCoins!',
                     'residence_relaxation', TIMESTAMPTZ '2026-08-16 18:00:00-04'),
                    ('Whose House? Mudge House!',
                     'Start your adventure (or visit a friend) in front of Mudge House!',
                     'During Orientation Week, tap your mobile device at an O-Quest Challenge Point to complete a Challenge and earn ScottyCoins!',
                     'residence_relaxation', TIMESTAMPTZ '2026-08-16 18:00:00-04'),
                    ('We Like Our Carrots With RANCH! (Rez on Fifth Edition)',
                     'Start your adventure (or visit a friend) in front of the Residence on Fifth Apartments!',
                     'During Orientation Week, tap your mobile device at an O-Quest Challenge Point to complete a Challenge and earn ScottyCoins!',
                     'residence_relaxation', TIMESTAMPTZ '2026-08-16 18:00:00-04'),
                    ('We Like Our Celery With RANCH! (Clyde House Edition)',
                     'Start your adventure (or visit a friend) in front of Clyde House!',
                     'During Orientation Week, tap your mobile device at an O-Quest Challenge Point to complete a Challenge and earn ScottyCoins!',
                     'residence_relaxation', TIMESTAMPTZ '2026-08-16 18:00:00-04'),
                    ('Stever Fever in the Atmosphere!',
                     'Start your adventure (or visit a friend) in front of Stever House!',
                     'During Orientation Week, tap your mobile device at an O-Quest Challenge Point to complete a Challenge and earn ScottyCoins!',
                     'residence_relaxation', TIMESTAMPTZ '2026-08-16 18:00:00-04'),
                    ('How Hot? Red Hot! (Hamerschlag Edition)',
                     'Start your adventure (or visit a friend) in front of Hamerschlag House!',
                     'During Orientation Week, tap your mobile device at an O-Quest Challenge Point to complete a Challenge and earn ScottyCoins!',
                     'residence_relaxation', TIMESTAMPTZ '2026-08-16 18:00:00-04')
            ) AS seed ("name", "tagline", "description", "category", "open_from")
            WHERE NOT EXISTS (SELECT 1 FROM "challenge");
"#;

// A challenge stays locked while "open_from" sits in the future (quest::taps::locked).
// Half the seeded rows, drawn at random, keep their published unlock time -- pushed
// out a week when that date has already passed -- and the rest open immediately.
// Only name-derived ids are considered, so this is a no-op when the seed was skipped.
const LOCK_HALF: &str = r#"
            WITH pick AS (
                SELECT "id", row_number() OVER (ORDER BY random()) AS "n"
                FROM "challenge"
                WHERE "id" = md5('oquest-2026:' || "name")::uuid
            )
            UPDATE "challenge"
            SET "open_from" = CASE
                WHEN pick."n" > 62 THEN now()
                WHEN "challenge"."open_from" > now() THEN "challenge"."open_from"
                ELSE now() + INTERVAL '7 days'
            END
            FROM pick
            WHERE "challenge"."id" = pick."id";
"#;

// Only rows this migration inserted carry a name-derived id, so content imported
// by hand (and anything tapped against it) survives a rollback.
const UNSEED: &str = r#"
            CREATE TEMP TABLE "seeded_challenge" AS
            SELECT "id" FROM "challenge"
            WHERE "id" = md5('oquest-2026:' || "name")::uuid;

            DELETE FROM "daily_challenge"
            WHERE "challenge_id" IN (SELECT "id" FROM "seeded_challenge");

            DELETE FROM "tap_events"
            WHERE "challenge_id" IN (SELECT "id" FROM "seeded_challenge");

            DELETE FROM "challenge_card"
            WHERE "challenge_id" IN (SELECT "id" FROM "seeded_challenge");

            DELETE FROM "challenge"
            WHERE "id" IN (SELECT "id" FROM "seeded_challenge");

            DROP TABLE "seeded_challenge";
"#;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        // One batch: the lock draw has to see the rows the seed just wrote, and a
        // pooled connection is not guaranteed to be the same one twice.
        manager
            .get_connection()
            .execute_unprepared(&[SEED, LOCK_HALF].concat())
            .await?;
        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager.get_connection().execute_unprepared(UNSEED).await?;
        Ok(())
    }
}
